site_name: QueryBench
site_url: https://querybench.com
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - navigation.indexes

nav:
  - Home: index.md
  - Methodology: methodology.md
  - Datasets: datasets.md
  - Queries: queries.md
  - Good benchmarks: good-benchmarks.md
  - Other Benchmarks:
    - h2o: other-benchmarks/h2o-pros-cons.md
    - ClickBench: other-benchmarks/clickbench-pros-cons.md
