site_name: QueryBench
site_url: https://querybench.com
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.expand
    - navigation.indexes
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Methodology: methodology.md
  - Datasets: datasets.md
  - Queries: queries.md
  - Good benchmarks: good-benchmarks.md
  - Other Benchmarks:
    - ClickBench: other-benchmarks/clickbench-pros-cons.md
    - h2o: other-benchmarks/h2o-pros-cons.md
    - PDS-H: other-benchmarks/polars-decision-support-pds-h.md
    - TPC-H: other-benchmarks/tpch-pros-cons.md
